# Generated by Django 3.1.7 on 2021-03-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_auto_20210324_1932'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cabeceracomandamodel',
            table='t_comanda_cabecera',
        ),
    ]
