# Generated by Django 3.1.7 on 2021-03-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_auto_20210324_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobantemodel',
            options={'verbose_name': 'Comprobante'},
        ),
        migrations.AlterModelTable(
            name='comprobantemodel',
            table='t_comprobante',
        ),
    ]
