# Generated by Django 3.1.7 on 2021-03-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_auto_20210324_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalmesamodel',
            options={'verbose_name': 'personal mesa'},
        ),
    ]
