# Generated by Django 3.1.7 on 2021-03-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0011_auto_20210329_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantemodel',
            name='comprobanteTipo',
            field=models.IntegerField(choices=[(1, 'BOLETA'), (2, 'FACTURA')], default=None),
            preserve_default=False,
        ),
    ]
