# Generated by Django 3.1.7 on 2021-03-18 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20210317_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especiemodel',
            name='especieNombre',
            field=models.CharField(db_column='especie_nombre', max_length=45, verbose_name='Nombre de la especie'),
        ),
        migrations.AlterField(
            model_name='razamodel',
            name='especie',
            field=models.ForeignKey(db_column='especie_id', help_text='Id de la Especie', on_delete=django.db.models.deletion.PROTECT, related_name='tiposespecie', to='administracion.especiemodel', unique=True, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='razamodel',
            name='razaId',
            field=models.AutoField(auto_created=True, db_column='raza_id', help_text='ID de la raza', primary_key=True, serialize=False, unique=True, verbose_name='ID de la raza'),
        ),
    ]
