# Generated by Django 3.1.7 on 2021-03-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20210318_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='especiemodel',
            name='especieEstado',
            field=models.BooleanField(db_column='especie_estado', default=True),
        ),
    ]
